### ISSUE TITLE
My crash report :( Can't break slabs with carpets on them w/o crashing game

### ISSUE THREAD

**Issue by krispytm-official** [EndlesNights/CarpetStairsMod#5]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 3/27/20 6:54 PM
Description: Exception while ticking

java.lang.IllegalArgumentException: Cannot get property BooleanProperty{name=waterlogged, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{minecraft:air}
	at net.minecraft.state.StateHolder.func_177229_b(SourceFile:93) ~[?:?] {re:classloading}
	at com.endlesnights.carpetstairsmod.blocks.CarpetSlab.func_196260_a(CarpetSlab.java:56) ~[?:1.0] {re:classloading}
	at net.minecraft.block.BlockState.func_196955_c(BlockState.java:302) ~[?:?] {re:classloading}
	at com.endlesnights.carpetstairsmod.blocks.CarpetSlab.func_196271_a(CarpetSlab.java:38) ~[?:1.0] {re:classloading}
	at net.minecraft.block.BlockState.func_196956_a(BlockState.java:286) ~[?:?] {re:classloading}
	at net.minecraft.block.Block.func_196242_c(Block.java:184) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.block.BlockState.func_196946_a(BlockState.java:233) ~[?:?] {re:classloading}
	at net.minecraft.world.World.markAndNotifyBlock(World.java:223) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.World.func_180501_a(World.java:190) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.fluid.FlowingFluid.func_205574_a(SourceFile:262) ~[?:?] {re:classloading}
	at net.minecraft.fluid.FlowingFluid.func_205575_a(SourceFile:135) ~[?:?] {re:classloading}
	at net.minecraft.fluid.FlowingFluid.func_207191_a(SourceFile:459) ~[?:?] {re:classloading}
	at net.minecraft.fluid.IFluidState.func_206880_a(IFluidState.java:68) ~[?:?] {re:classloading,xf:fml:forgeendertech:randomTickFluid}
	at net.minecraft.world.server.ServerWorld.func_205339_a(ServerWorld.java:574) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld$$Lambda$7738/2121001762.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.server.ServerTickList.func_205365_a(SourceFile:87) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:317) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.state.StateHolder.func_177229_b(SourceFile:93)
	at com.endlesnights.carpetstairsmod.blocks.CarpetSlab.func_196260_a(CarpetSlab.java:56)
	at net.minecraft.block.BlockState.func_196955_c(BlockState.java:302)
	at com.endlesnights.carpetstairsmod.blocks.CarpetSlab.func_196271_a(CarpetSlab.java:38)
	at net.minecraft.block.BlockState.func_196956_a(BlockState.java:286)
	at net.minecraft.block.Block.func_196242_c(Block.java:184)
	at net.minecraft.block.BlockState.func_196946_a(BlockState.java:233)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:223)
	at net.minecraft.world.World.func_180501_a(World.java:190)
	at net.minecraft.fluid.FlowingFluid.func_205574_a(SourceFile:262)
	at net.minecraft.fluid.FlowingFluid.func_205575_a(SourceFile:135)
	at net.minecraft.fluid.FlowingFluid.func_207191_a(SourceFile:459)
	at net.minecraft.fluid.IFluidState.func_206880_a(IFluidState.java:68)
	at net.minecraft.world.server.ServerWorld.func_205339_a(ServerWorld.java:574)
	at net.minecraft.world.server.ServerWorld$$Lambda$7738/2121001762.accept(Unknown Source)

-- Block being ticked --
Details:
	Block location: World: (9263,65,4590), Chunk: (at 15,4,14 in 578,286; contains blocks 9248,0,4576 to 9263,255,4591), Region: (18,8; contains chunks 576,256 to 607,287, blocks 9216,0,4096 to 9727,255,4607)
Stacktrace:
	at net.minecraft.world.server.ServerTickList.func_205365_a(SourceFile:87)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:317)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['krispytm'/31, l='New World', x=9262.19, y=64.20, z=4592.01]]
	Chunk stats: ServerChunkCache: 3394
	Level dimension: DimensionType{minecraft:overworld}
	Level name: New World
	Level seed: 1742202349537423335
	Level generator: ID 07 - islands, ver 0. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (6832,84,5822), Chunk: (at 0,5,14 in 427,363; contains blocks 6832,0,5808 to 6847,255,5823), Region: (13,11; contains chunks 416,352 to 447,383, blocks 6656,0,5632 to 7167,255,6143)
	Level time: 283290 game time, 283290 day time
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 43693 (now: false), thunder time: 71685 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 579735168 bytes (552 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.18
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		Kiwi-1.15.2-2.6.5.jar Kiwi {kiwi@2.6.5 DONE}
		flamboyant-2.0.1.jar Flamboyant {flamboyant@2.0.1 DONE}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 DONE}
		vanillathings-1.15.2-0.5.7.jar Vanilla Things {vanillathings@0.5.7 DONE}
		prefab-1.5.0.2.jar Prefab {prefab@1.5.0.2 DONE}
		buzzierbees-1.1.5.jar Buzzier Bees {buzzierbees@1.1.5 DONE}
		mcw-windows-1.0.0-mc1.15.1_1.15.2.jar Macaw's Windows {mcwwindows@1.0.0 DONE}
		bloomful-1.15.2-1.3.jar Bloomful {bloomful@NONE DONE}
		Island_Generator[1.15.2]-1.2.0.jar Island Generator {islandgenerator@1.2.0 DONE}
		ForgeEndertech-1.15.2-6.0.0.0-build.0004.jar Forge Endertech {forgeendertech@6.0.0.0 DONE}
		essentialfeatures-3.1.0.jar Essential Features {essentialfeatures@3.1.0 DONE}
		Vanilla-Crafts-and-Expansion-20200326b.jar Vanilla Crafts & Expansion {vanillaexpansion@20200304a DONE}
		railladderpower-1.15.2-1.0.0.jar Scaffolding power for rails and ladders Mod {ladderpower@1.15.2-1.0.0 DONE}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 DONE}
		additionalbars-1.2.2.jar Additional Bars {additionalbars@1.2.2 DONE}
		WorldTweaker-1.0.jar World Tweaker {worldtweaker@1.0 DONE}
		premium-wood-1.15.2-1.1.0.jar Premium Wood {premium_wood@1.1.0 DONE}
		decorative_blocks-6d.jar Decorative Blocks {decorative_blocks@1.6 DONE}
		Bookshelf-1.15.2-5.1.3.jar Bookshelf {bookshelf@5.1.3 DONE}
		u_team_core-1.15.2-2.10.6.155.jar U Team Core {uteamcore@2.10.6.155 DONE}
		mapperbase-1.15.2-1.0.0.0.jar Mapper Base {mapperbase@1.15.2-1.0.0.0 DONE}
		bedspreads-FORGE-1.15.2-3.0.jar Bedspreads {bedspreads@FORGE-1.15.2-3.0 DONE}
		carpetstairsmod-mc1.15-v1.3.1.jar Carpet Stairs Mod {carpetstairsmod@1.3.1 DONE}
		forge-1.15.2-31.1.18-universal.jar Forge {forge@31.1.18 DONE}
		amb-1.15.2-0.5.0.jar Aurum's More Blocks {amb@1.15.2-0.5.0 DONE}
		PattysMoreStuff-Stable-1.15.2-1.2.4.jar pattysmorestuff {pattysmorestuff@1.2.4 DONE}
		EE+-+2.0.jar Extra Enrichments {extraenrichments@2.0 DONE}
		forge-1.15.2-31.1.18-client.jar Minecraft {minecraft@1.15.2 DONE}
		delicateanddainty-.1.jar Delicate and Dainty! {delicateanddainty@.1 DONE}
		compressedblocks-1.15.2-2.3.1.jar compressedblocks {compressedblocks@2.3.1 DONE}
		useful_backpacks-1.15.2-1.9.4.63.jar Useful Backpacks {usefulbackpacks@1.9.4.63 DONE}
		repurposedstructures-1.15.2-1.1.0.jar Repurposed Structures {repurposed_structures@1.15.2-1.1.0 DONE}
		embellishcraft-1.15.2-2.0.0.0.jar EmbellishCraft {embellishcraft@1.15.2-2.0.0.0 DONE}
		BiomesOPlenty-1.15.2-10.0.0.353-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.353 DONE}
		valhelsia_structures-15.0.2a.jar Valhelsia Structures {valhelsia_structures@15.0.2a DONE}
		beesknees-1.15.2-1.0.1.jar The Bees Knees Mod {beesknees@1 DONE}
		AdLods-1.15.2-3.0.0.0-build.0004.jar Large Ore Deposits {adlods@3.0.0.0 DONE}
		hgp-1.15.2.jar Horizontal Glass Panes {hgp@1.15.2 DONE}
		simplefarming-1.15.2-1.2.7.jar Simple Farming {simplefarming@1.15.2-1.2.7 DONE}
		ElementMod-1.15.2-1.0.6.jar ElementMod {elementmod@1.15.2-1.0.6 DONE}
		atmospheric-1.15.2-1.2.jar Atmospheric {atmospheric@1.2 DONE}
		MiscAdditions-1.2.2.jar Misc Additions {miscadditions@1.2.2 DONE}
		Patchouli-1.15.2-1.2-28.jar Patchouli {patchouli@1.15.2-1.2-28 DONE}
		BasseBombeCraft-1.15.2-1.39.jar BasseBombeCraft Mod {bassebombecraft@1.15.2-1.39 DONE}
		roadstuff-1.15.2-3.0.0.jar Road Stuff {roadstuff@1.15.2-3.0.0 DONE}
		extlights-2.0.jar Extended Lights {extlights@2.0 DONE}
		corail_recycler-4.0.3-1.15.2.jar Corail Recycler {corail_recycler@4.0.3 DONE}
		2014-1.0.0.jar §b2014 {nostalgia@1.0.0 DONE}
		DoubleSlabs-1.15-2.0.2.jar Double Slabs {doubleslabs@2.0.2 DONE}
		libnonymous-1.15.2-1.1.1.5.jar Libnonymous {libnonymous@1.1.1.5 DONE}
		Gobber2-1.15.2-2.2.64.jar Gobber 2 {gobber2@2.2.64 DONE}
		obfuscate-0.3.4-1.15.2.jar Obfuscate {obfuscate@0.3.4 DONE}
		vehicle-mod-0.43.5-1.15.2.jar MrCrayfish's Vehicle Mod {vehicle@0.43.5 DONE}
		mcw-roofs-1.0.2-mc1.15.2_1.15.1.jar Macaw's Roofs {mcwroofs@1.0.2 DONE}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		simplecoloredblocks-2.0.0a.jar Simple Colored Blocks {simplecoloredblocks@2.0.0a DONE}
		ilikewood-1.15.2-2.2.0.1.jar I Like Wood {ilikewood@1.15.2-2.2.0.1 DONE}
		Biomes_You_Go_0.1.5.jar Oh The Biomes You'll Go {byg@0.0.1 DONE}
	Kiwi Modules: 
		kiwi:contributors
	Player Count: 1 / 8; [ServerPlayerEntity['krispytm'/31, l='New World', x=9262.19, y=64.20, z=4592.01]]
	Data Packs: vanilla, mod:additionalbars, mod:adlods (incompatible), mod:amb, mod:atmospheric, mod:bassebombecraft (incompatible), mod:bedspreads (incompatible), mod:beesknees (incompatible), mod:biomesoplenty, mod:bloomful (incompatible), mod:bookshelf (incompatible), mod:buzzierbees, mod:byg, mod:carpetstairsmod, mod:cfm (incompatible), mod:compressedblocks (incompatible), mod:corail_recycler, mod:decorative_blocks, mod:delicateanddainty, mod:doubleslabs, mod:elementmod, mod:embellishcraft (incompatible), mod:essentialfeatures (incompatible), mod:extlights, mod:extraenrichments, mod:flamboyant (incompatible), mod:forge (incompatible), mod:forgeendertech (incompatible), mod:gobber2 (incompatible), mod:hgp (incompatible), mod:ilikewood, mod:islandgenerator, mod:jei (incompatible), mod:kiwi, mod:ladderpower (incompatible), mod:libnonymous (incompatible), mod:mapperbase, mod:mcwroofs, mod:mcwwindows, mod:miscadditions, mod:naturescompass (incompatible), mod:nostalgia, mod:obfuscate (incompatible), mod:patchouli (incompatible), mod:pattysmorestuff (incompatible), mod:prefab, mod:premium_wood (incompatible), mod:repurposed_structures, mod:roadstuff (incompatible), mod:simplecoloredblocks, mod:simplefarming, mod:usefulbackpacks, mod:uteamcore, mod:valhelsia_structures (incompatible), mod:vanillaexpansion (incompatible), mod:vanillathings, mod:vehicle (incompatible), mod:worldtweaker
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by EndlesNights** [comment]
Should be fixed now, in latest patch. Thanks for the reports.
 (Made a slight mistake in the isValidPosistion class, checking first if the block was waterlogged rather than if it could be.)
